
server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
       globalcors:
        add-to-simple-url-handler-mapping: true

        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "User-Key"
              - "Request-Tracker"
              - "Session-Tracker"
              - "X-XSRF-TOKEN"
              - "X-IBM-CLIENT-ID"
              - "Message-ID"
              - "X-IBM-CLIENT-SECRET"
       default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
       routes:
        - id: EMPLOYEEDETAILS
          uri: http://localhost:8081
          predicates:
            - Path=/employeedetails/**
          filters: AuthenticationFilter
            
        - id: MENTORDETAILS
          uri: http://localhost:8082
          predicates:
            - Path=/mentors/**
          filters: AuthenticationFilter
            
        - id: BATCHDETAILS
          uri: http://localhost:8083
          predicates:
            - Path=/batch/**
          filters: AuthenticationFilter
            
        - id: COURSES
          uri: http://localhost:8084
          predicates:
            - Path=/courses/**
          filters: AuthenticationFilter
            
        - id: DAILYUPDATES
          uri: http://localhost:8085
          predicates:
            - Path=/dailyupdates/**
          filters: AuthenticationFilter
            
        - id: GEMINI
          uri: http://localhost:8086
          predicates:
            - Path=/geminichat/**
          filters: AuthenticationFilter
          
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**
          filters: AuthenticationFilter
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true

        
          